repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0   # pick a specific Black release (check PyPI for latest)
    hooks:
      - id: black

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.8  # Use the official pylint repository and a compatible version for Python 3.13
    hooks:
      - id: pylint
        args: ["--disable=C0114,C0115,C0116"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
